config/routes.rb
Rails.application.routes.draw do

  resources :coverage_reports
  resources :coverage_targets
  resources :coverage_files
  resources :functions
  root 'coverage_reports#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/function.rb
class Function < ApplicationRecord

  belongs_to :coverage_file

  def self.make_function(coverage_file, json)

    # JSON format:
    # {
    #    "coveredLines": 0,
    #    "lineCoverage": 0,
    #    "lineNumber": 25,
    #    "executionCount": 0,
    #    "name": "...",
    #    "executableLines": 6
    #  }

    function = Function.create() do |f|
      f.covered_lines = json['coveredLines'].to_i
      f.line_coverage = json['lineCoverage'].to_f
      f.line_number = json['lineNumber'].to_i
      f.execution_count = json['executionCount'].to_i
      f.name = json['name']
      f.executable_lines = json['executableLines'].to_i
    end

    function.coverage_file = coverage_file

    function
  end

end

app/controllers/functions_controller.rb
class FunctionsController < ApplicationController
  before_action :set_function, only: [:show, :edit, :update, :destroy]

  # GET /functions
  # GET /functions.json
  def index
    @functions = Function.order(line_coverage: :desc).each do |f|
      f.line_coverage *= 100
    end
  end

  # GET /functions/1
  # GET /functions/1.json
  def show
  end

  # GET /functions/new
  def new
    @function = Function.new
  end

  # GET /functions/1/edit
  def edit
  end

  # POST /functions
  # POST /functions.json
  def create
    @function = Function.new(function_params)

    respond_to do |format|
      if @function.save
        format.html { redirect_to @function, notice: 'Function was successfully created.' }
        format.json { render :show, status: :created, location: @function }
      else
        format.html { render :new }
        format.json { render json: @function.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /functions/1
  # PATCH/PUT /functions/1.json
  def update
    respond_to do |format|
      if @function.update(function_params)
        format.html { redirect_to @function, notice: 'Function was successfully updated.' }
        format.json { render :show, status: :ok, location: @function }
      else
        format.html { render :edit }
        format.json { render json: @function.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /functions/1
  # DELETE /functions/1.json
  def destroy
    @function.destroy
    respond_to do |format|
      format.html { redirect_to functions_url, notice: 'Function was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_function
      @function = Function.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def function_params
      params.require(:function).permit(:name, :covered_lines, :line_coverage, :line_number, :execution_count, :executable_lines)
    end
end

app/helpers/functions_helper.rb
module FunctionsHelper

  def row_class(function)
    if function.line_coverage > 0.75
      "bg-success"
    else
      function.line_coverage > 0.50 ? "bg-warning" : "bg-danger"
    end
  end

  def number_to_code_coverage_percentage(number)
    number_to_percentage(number * 100, precision: 2)
  end

end

app/views/functions/_form.html.erb
<%= form_with(model: function, local: true) do |form| %>
  <% if function.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(function.errors.count, "error") %> prohibited this function from being saved:</h2>

      <ul>
        <% function.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :covered_lines %>
    <%= form.number_field :covered_lines %>
  </div>

  <div class="field">
    <%= form.label :line_coverage %>
    <%= form.text_field :line_coverage %>
  </div>

  <div class="field">
    <%= form.label :line_number %>
    <%= form.number_field :line_number %>
  </div>

  <div class="field">
    <%= form.label :execution_count %>
    <%= form.number_field :execution_count %>
  </div>

  <div class="field">
    <%= form.label :executable_lines %>
    <%= form.number_field :executable_lines %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/functions/edit.html.erb
<h1>Editing Function</h1>

<%= render 'form', function: @function %>

<%= link_to 'Show', @function %> |
<%= link_to 'Back', functions_path %>

app/views/functions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Functions</h1>

<div class="table-responsive">
  <table class="table">
    <thead>
      <tr>
        <th><div class="th-inner sortable both">Name</div></th>
        <th>Covered lines</th>
        <th>Line coverage</th>
        <th>Line number</th>
        <th>Execution count</th>
        <th>Executable lines</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @functions.each do |function| %>
        <tr class=<%= if function.line_coverage > 75
                        "bg-success"
                      else
                        function.line_coverage > 35 ? "bg-warning" : "bg-danger"
                      end %> >
          <td><%= function.name %></td>
          <td><%= function.covered_lines %></td>
          <td><%= function.line_coverage %>%</td>
          <td><%= function.line_number %></td>
          <td><%= function.execution_count %></td>
          <td><%= function.executable_lines %></td>
          <td><%= link_to 'Show', function %></td>
          <td><%= link_to 'Edit', edit_function_path(function) %></td>
          <td><%= link_to 'Destroy', function, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<br>

<%= link_to 'New Function', new_function_path %>

app/views/functions/new.html.erb
<h1>New Function</h1>

<%= render 'form', function: @function %>

<%= link_to 'Back', functions_path %>

app/views/functions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @function.name %>
</p>

<p>
  <strong>Covered lines:</strong>
  <%= @function.covered_lines %>
</p>

<p>
  <strong>Line coverage:</strong>
  <%= @function.line_coverage %>
</p>

<p>
  <strong>Line number:</strong>
  <%= @function.line_number %>
</p>

<p>
  <strong>Execution count:</strong>
  <%= @function.execution_count %>
</p>

<p>
  <strong>Executable lines:</strong>
  <%= @function.executable_lines %>
</p>

<%= link_to 'Edit', edit_function_path(@function) %> |
<%= link_to 'Back', functions_path %>