config/routes.rb
Rails.application.routes.draw do

  resources :coverage_reports
  resources :coverage_targets
  resources :coverage_files
  resources :functions
  root 'coverage_reports#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/coverage_target.rb
class CoverageTarget < ApplicationRecord
  belongs_to :coverage_report
  has_many :coverage_files, dependent: :destroy

  def self.make_target(coverage_report, json)
    # JSON format:
    # {
    #    "coveredLines": 0,
    #    "lineCoverage": 1,
    #    "files": [ ... ],
    #    "name": "...",
    #    "executableLines": 79,
    #    "buildProductPath": "..."
    #  }

    coverage_target = CoverageTarget.create do |target|
      target.covered_lines = json['coveredLines'].to_i
      target.line_coverage = json['lineCoverage'].to_f
      target.name = json['name']
      target.executable_lines = json['executableLines'].to_i
      target.build_product_path = json['buildProductPath']

      files = []

      files_json = json['files']
      files_json.each do |file_json|
        files.push(CoverageFile.make_file(target, file_json))
      end

      target.coverage_files = files
      target.coverage_report = coverage_report
    end

    coverage_target
  end
end

app/controllers/coverage_targets_controller.rb
class CoverageTargetsController < ApplicationController
  before_action :set_coverage_target, only: [:show, :edit, :update, :destroy]

  # GET /coverage_targets
  # GET /coverage_targets.json
  def index
    @coverage_targets = CoverageTarget.all.each do |target|
      target.line_coverage = (target.line_coverage * 100).round(2)
    end
  end

  # GET /coverage_targets/1
  # GET /coverage_targets/1.json
  def show
  end

  # GET /coverage_targets/new
  def new
    @coverage_target = CoverageTarget.new
  end

  # GET /coverage_targets/1/edit
  def edit
  end

  # POST /coverage_targets
  # POST /coverage_targets.json
  def create
    @coverage_target = CoverageTarget.new(coverage_target_params)

    respond_to do |format|
      if @coverage_target.save
        format.html { redirect_to @coverage_target, notice: 'Coverage target was successfully created.' }
        format.json { render :show, status: :created, location: @coverage_target }
      else
        format.html { render :new }
        format.json { render json: @coverage_target.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coverage_targets/1
  # PATCH/PUT /coverage_targets/1.json
  def update
    respond_to do |format|
      if @coverage_target.update(coverage_target_params)
        format.html { redirect_to @coverage_target, notice: 'Coverage target was successfully updated.' }
        format.json { render :show, status: :ok, location: @coverage_target }
      else
        format.html { render :edit }
        format.json { render json: @coverage_target.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coverage_targets/1
  # DELETE /coverage_targets/1.json
  def destroy
    @coverage_target.destroy
    respond_to do |format|
      format.html { redirect_to coverage_targets_url, notice: 'Coverage target was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_coverage_target
      @coverage_target = CoverageTarget.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def coverage_target_params
      params.require(:coverage_target).permit(:covered_lines, :line_coverage, :name, :executable_lines, :build_product_path, :coverage_report_id)
    end
end

app/helpers/coverage_targets_helper.rb
module CoverageTargetsHelper
end

app/views/coverage_targets/_form.html.erb
<%= form_with(model: coverage_target, local: true) do |form| %>
  <% if coverage_target.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(coverage_target.errors.count, "error") %> prohibited this coverage_target from being saved:</h2>

      <ul>
        <% coverage_target.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :covered_lines %>
    <%= form.text_field :covered_lines %>
  </div>

  <div class="field">
    <%= form.label :line_coverage %>
    <%= form.text_field :line_coverage %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :executable_lines %>
    <%= form.text_field :executable_lines %>
  </div>

  <div class="field">
    <%= form.label :build_product_path %>
    <%= form.text_field :build_product_path %>
  </div>

  <div class="field">
    <%= form.label :coverage_report_id %>
    <%= form.text_field :coverage_report_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/coverage_targets/edit.html.erb
<h1>Editing Coverage Target</h1>

<%= render 'form', coverage_target: @coverage_target %>

<%= link_to 'Show', @coverage_target %> |
<%= link_to 'Back', coverage_targets_path %>

app/views/coverage_targets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Coverage Targets</h1>

<table>
  <thead>
    <tr>
      <th>Covered lines</th>
      <th>Line coverage</th>
      <th>Name</th>
      <th>Executable lines</th>
      <th>Build product path</th>
      <th>Coverage report</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @coverage_targets.each do |coverage_target| %>
      <tr>
        <td><%= coverage_target.covered_lines %></td>
        <td><%= coverage_target.line_coverage %></td>
        <td><%= coverage_target.name %></td>
        <td><%= coverage_target.executable_lines %></td>
        <td><%= coverage_target.build_product_path %></td>
        <td><%= coverage_target.coverage_report_id %></td>
        <td><%= link_to 'Show', coverage_target %></td>
        <td><%= link_to 'Edit', edit_coverage_target_path(coverage_target) %></td>
        <td><%= link_to 'Destroy', coverage_target, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Coverage Target', new_coverage_target_path %>

app/views/coverage_targets/new.html.erb
<h1>New Coverage Target</h1>

<%= render 'form', coverage_target: @coverage_target %>

<%= link_to 'Back', coverage_targets_path %>

app/views/coverage_targets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Covered lines:</strong>
  <%= @coverage_target.covered_lines %>
</p>

<p>
  <strong>Line coverage:</strong>
  <%= @coverage_target.line_coverage %>
</p>

<p>
  <strong>Name:</strong>
  <%= @coverage_target.name %>
</p>

<p>
  <strong>Executable lines:</strong>
  <%= @coverage_target.executable_lines %>
</p>

<p>
  <strong>Build product path:</strong>
  <%= @coverage_target.build_product_path %>
</p>

<p>
  <strong>Coverage report:</strong>
  <%= @coverage_target.coverage_report_id %>
</p>

<%= link_to 'Edit', edit_coverage_target_path(@coverage_target) %> |
<%= link_to 'Back', coverage_targets_path %>