config/routes.rb
Rails.application.routes.draw do

  resources :coverage_reports
  resources :coverage_targets
  resources :coverage_files
  resources :functions
  root 'coverage_reports#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/coverage_file.rb
class CoverageFile < ApplicationRecord
  belongs_to :coverage_target
  has_many :functions, dependent: :destroy

  def self.make_file(coverage_target, json)
    # JSON format:
    # {
    #    "coveredLines": 0,
    #    "lineCoverage": 1,
    #    "path": "...",
    #    "functions": [ ... ],
    #    "name": "...",
    #    "executableLines": 79
    #  }

    functions = []

    coverage_file = CoverageFile.create do |file|
      file.covered_lines = json['coveredLines'].to_i
      file.line_coverage = json['lineCoverage'].to_f
      file.path = json['path']
      file.name = json['name']
      file.executable_lines = json['executableLines'].to_i
      file.functions

      functions_json = json['functions']
      functions_json.each do |function_json|
        functions.push(Function.make_function(file, function_json))
      end
    end

    coverage_file.functions = functions
    coverage_file.coverage_target = coverage_target

    coverage_file
  end
end

app/controllers/coverage_files_controller.rb
class CoverageFilesController < ApplicationController
  before_action :set_coverage_file, only: [:show, :edit, :update, :destroy]

  # GET /coverage_files
  # GET /coverage_files.json
  def index
    @coverage_files = CoverageFile.all
  end

  # GET /coverage_files/1
  # GET /coverage_files/1.json
  def show
  end

  # GET /coverage_files/new
  def new
    @coverage_file = CoverageFile.new
  end

  # GET /coverage_files/1/edit
  def edit
  end

  # POST /coverage_files
  # POST /coverage_files.json
  def create
    @coverage_file = CoverageFile.new(coverage_file_params)

    respond_to do |format|
      if @coverage_file.save
        format.html { redirect_to @coverage_file, notice: 'Coverage file was successfully created.' }
        format.json { render :show, status: :created, location: @coverage_file }
      else
        format.html { render :new }
        format.json { render json: @coverage_file.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coverage_files/1
  # PATCH/PUT /coverage_files/1.json
  def update
    respond_to do |format|
      if @coverage_file.update(coverage_file_params)
        format.html { redirect_to @coverage_file, notice: 'Coverage file was successfully updated.' }
        format.json { render :show, status: :ok, location: @coverage_file }
      else
        format.html { render :edit }
        format.json { render json: @coverage_file.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coverage_files/1
  # DELETE /coverage_files/1.json
  def destroy
    @coverage_file.destroy
    respond_to do |format|
      format.html { redirect_to coverage_files_url, notice: 'Coverage file was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_coverage_file
      @coverage_file = CoverageFile.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def coverage_file_params
      params.require(:coverage_file).permit(:covered_lines, :line_coverage, :path, :name, :executable_lines, :coverage_target_id)
    end
end

app/helpers/coverage_files_helper.rb
module CoverageFilesHelper

  def sorted_functions(functions)
    functions.order(line_coverage: :desc, execution_count: :desc, executable_lines: :desc)
  end

end

app/views/coverage_files/_form.html.erb
<%= form_with(model: coverage_file, local: true) do |form| %>
  <% if coverage_file.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(coverage_file.errors.count, "error") %> prohibited this coverage_file from being saved:</h2>

      <ul>
        <% coverage_file.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :covered_lines %>
    <%= form.number_field :covered_lines %>
  </div>

  <div class="field">
    <%= form.label :line_coverage %>
    <%= form.text_field :line_coverage %>
  </div>

  <div class="field">
    <%= form.label :path %>
    <%= form.text_field :path %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :executable_lines %>
    <%= form.text_field :executable_lines %>
  </div>

  <div class="field">
    <%= form.label :coverage_target_id %>
    <%= form.text_field :coverage_target_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/coverage_files/edit.html.erb
<h1>Editing Coverage File</h1>

<%= render 'form', coverage_file: @coverage_file %>

<%= link_to 'Show', @coverage_file %> |
<%= link_to 'Back', coverage_files_path %>

app/views/coverage_files/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Coverage Files</h1>

<table>
  <thead>
    <tr>
      <th>Covered lines</th>
      <th>Line coverage</th>
      <th>Path</th>
      <th>Name</th>
      <th>Executable lines</th>
      <th>Coverage target</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @coverage_files.each do |coverage_file| %>
      <tr>
        <td><%= coverage_file.covered_lines %></td>
        <td><%= coverage_file.line_coverage %></td>
        <td><%= coverage_file.path %></td>
        <td><%= coverage_file.name %></td>
        <td><%= coverage_file.executable_lines %></td>
        <td><%= coverage_file.coverage_target_id %></td>
        <td><%= link_to 'Show', coverage_file %></td>
        <td><%= link_to 'Edit', edit_coverage_file_path(coverage_file) %></td>
        <td><%= link_to 'Destroy', coverage_file, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Coverage File', new_coverage_file_path %>

app/views/coverage_files/new.html.erb
<h1>New Coverage File</h1>

<%= render 'form', coverage_file: @coverage_file %>

<%= link_to 'Back', coverage_files_path %>

app/views/coverage_files/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Covered lines:</strong>
  <%= @coverage_file.covered_lines %>
</p>

<p>
  <strong>Line coverage:</strong>
  <%= @coverage_file.line_coverage %>
</p>

<p>
  <strong>Path:</strong>
  <%= @coverage_file.path %>
</p>

<p>
  <strong>Name:</strong>
  <%= @coverage_file.name %>
</p>

<p>
  <strong>Executable lines:</strong>
  <%= @coverage_file.executable_lines %>
</p>

<p>
  <strong>Coverage target:</strong>
  <%= @coverage_file.coverage_target_id %>
</p>

<%= link_to 'Edit', edit_coverage_file_path(@coverage_file) %> |
<%= link_to 'Back', coverage_files_path %>