config/routes.rb
Rails.application.routes.draw do

  resources :coverage_reports
  resources :coverage_targets
  resources :coverage_files
  resources :functions
  root 'coverage_reports#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/coverage_report.rb
class CoverageReport < ApplicationRecord
  has_many :coverage_targets, dependent: :destroy

  def self.make_report(json)
    coverage_report = CoverageReport.create do |report|
      report.covered_lines = json['coveredLines'].to_i
      report.line_coverage = json['lineCoverage'].to_f
      report.executable_lines = json['executableLines'].to_i

      targets_json = json['targets']
      targets_json.each do |target_json|
        CoverageTarget.make_target(report, target_json)
      end
    end

    coverage_report
  end
end

app/controllers/coverage_reports_controller.rb
class CoverageReportsController < ApplicationController
  protect_from_forgery prepend: true
  before_action :set_coverage_report, only: [:show, :edit, :update, :destroy]
  helper CoverageReportsHelper
  helper FunctionsHelper
  helper CoverageFilesHelper

  # GET /coverage_reports
  # GET /coverage_reports.json
  def index
    @coverage_reports = CoverageReport.all.each do |report|
      report.line_coverage = (report.line_coverage * 100).round(2)
    end
  end

  # GET /coverage_reports/1
  # GET /coverage_reports/1.json
  def show
  end

  # GET /coverage_reports/new
  def new
    @coverage_report = CoverageReport.new
  end

  # GET /coverage_reports/1/edit
  def edit
  end

  # POST /coverage_reports
  # POST /coverage_reports.json
  def create
    @coverage_report = CoverageReport.make_report(coverage_report_params)

    respond_to do |format|
      if @coverage_report.save
        format.html { redirect_to @coverage_report, notice: 'Coverage report was successfully created.' }
        format.json { render :show, status: :created, location: @coverage_report }
      else
        format.html { render :new }
        format.json { render json: @coverage_report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coverage_reports/1
  # PATCH/PUT /coverage_reports/1.json
  def update
    respond_to do |format|
      if @coverage_report.update(coverage_report_params)
        format.html { redirect_to @coverage_report, notice: 'Coverage report was successfully updated.' }
        format.json { render :show, status: :ok, location: @coverage_report }
      else
        format.html { render :edit }
        format.json { render json: @coverage_report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coverage_reports/1
  # DELETE /coverage_reports/1.json
  def destroy
    @coverage_report.destroy
    respond_to do |format|
      format.html { redirect_to coverage_reports_url, notice: 'Coverage report was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_coverage_report
      @coverage_report = CoverageReport.find(params[:id])
      @coverage_targets = @coverage_report.coverage_targets
    end

    # Only allow a list of trusted parameters through.
    def coverage_report_params
      file = params.require(:file)
      json = JSON.load File.open(file.tempfile)
      json
    end
end

app/helpers/coverage_reports_helper.rb
module CoverageReportsHelper

  def sorted_files(files)
    files.order(:name)
  end

end

app/views/coverage_reports/_form.html.erb
<%= form_with(model: coverage_report, local: true) do |form| %>
  <% if coverage_report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(coverage_report.errors.count, "error") %> prohibited this coverage_report from being saved:</h2>

      <ul>
        <% coverage_report.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :covered_lines %>
    <%= form.text_field :covered_lines %>
  </div>

  <div class="field">
    <%= form.label :line_coverage %>
    <%= form.text_field :line_coverage %>
  </div>

  <div class="field">
    <%= form.label :coverage_targets %>
    <%= form.text_field :coverage_targets %>
  </div>

  <div class="field">
    <%= form.label :executable_lines %>
    <%= form.text_field :executable_lines %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/coverage_reports/edit.html.erb
<h1>Editing Coverage Report</h1>

<%= render 'form', coverage_report: @coverage_report %>

<%= link_to 'Show', @coverage_report %> |
<%= link_to 'Back', coverage_reports_path %>

app/views/coverage_reports/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="text-center">Code Coverage Report - TurnipTime</h1>

<% if @coverage_reports.count > 0 %>
  <canvas id="myChart" width="400" height="100"></canvas>
  <script>
      var ctx = document.getElementById('myChart');
      var color = Chart.helpers.color;
      var myChart = new Chart(ctx, {
          type: 'line',
          data: {
              labels: <%= @coverage_reports.map { |report| report.id } %>,
              datasets: [
                  {
                      label: 'Executable Lines',
                      data: <%= @coverage_reports.map { |report| report.executable_lines } %>,
                      backgroundColor: 'rgba(255, 99, 132, 0.1)',
                      borderColor: 'rgba(255, 99, 132, 0.1)',
                      pointBorderColor: 'rgba(255, 99, 132, 0.5)',
                      pointBackgroundColor: 'rgba(255, 99, 132, 0.5)',
                      borderWidth: 1,
                      fill: true
                  },
                  {
                      // #129, 225, 120
                      label: 'Covered Lines',
                      data: <%= @coverage_reports.map { |report| report.covered_lines } %>,
                      backgroundColor: 'rgba(129, 225, 120, 1.0)',
                      borderColor: 'rgba(129, 225, 120, 1.0)',
                      pointBorderColor: 'rgba(99, 190, 91, 1.0)',
                      pointBackgroundColor: 'rgba(99, 190, 91, 1.0)',
                      borderWidth: 1,
                      fill: true
                  }
              ]

          },
          options: {
              scales: {
                  yAxes: [{
                      ticks: {
                          beginAtZero: true
                      }
                  }]
              }
          }
      });
  </script>

  <div class="table-responsive">
    <table class="table">
      <thead>
      <tr>
        <th>Covered lines</th>
        <th>Executable lines</th>
        <th>Line coverage</th>
        <th># of Targets</th>
        <th>Report Uploaded</th>
        <th colspan="2"></th>
      </tr>
      </thead>

      <tbody>
      <% @coverage_reports.each do |coverage_report| %>
        <tr>
          <td><%= number_with_delimiter(coverage_report.covered_lines) %></td>
          <td><%= number_with_delimiter(coverage_report.executable_lines) %></td>
          <td><%= number_to_percentage(coverage_report.line_coverage, precision: 2) %></td>
          <td><%= coverage_report.coverage_targets.count %></td>
          <td><%= coverage_report.created_at.strftime("%b %d, %Y at %l:%I:%M %P") %></td>
          <td><%= link_to 'More Details', coverage_report %></td>
          <td><%= link_to 'Delete', coverage_report, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
<% else %>
  <p class="lead text-center">No reports were found. Upload some reports from Xcode to see trends. 📈<br>
  You can upload a report by doing a POST to <code>localhost:3000/coverage_reports/</code>.</p>
<% end %>

<br>

<%#= link_to 'New Coverage Report', new_coverage_report_path %>

app/views/coverage_reports/new.html.erb
<h1>New Coverage Report</h1>

<%= render 'form', coverage_report: @coverage_report %>

<%= link_to 'Back', coverage_reports_path %>

app/views/coverage_reports/show.html.erb
<p id="notice"><%= notice %></p>

<% @coverage_targets.each do |target| %>
  <h2><%= target.name %></h2>
  <h3>Insights</h3>
  <% no_code_coverage_files = sorted_files(target.coverage_files).select { |f| f.line_coverage == 0.0 } %>
  <% decent_code_coverage_files = sorted_files(target.coverage_files).select { |f| f.line_coverage >= 0.90 } %>
  <% if no_code_coverage_files.count > 0 %>
    <div class="alert alert-danger" role="alert">
      The following files have 0% code coverage! 😨
    </div>
    <% no_code_coverage_files.sort_by { |f| -f.executable_lines }.each do |file| %>
      <ul><a href="#<%= file.name %>"><%= file.name %></a> (<%= file.executable_lines %> lines executed)</ul>
    <% end %>
  <% end %>
  <% if decent_code_coverage_files.count > 0 %>
    <div class="alert alert-success" role="alert">
      The following files have at least 90% code coverage. That's awesome! 🎉
    </div>
    <% decent_code_coverage_files.each do |file| %>
      <ul><a href="#<%= file.name %>"><%= file.name %></a></ul>
    <% end %>
  <% end %>
  <% sorted_files(target.coverage_files).each_with_index do |file, index| %>
    <h3 id="<%= file.name %>"><%= file.name %></h3>
    <h4></h4>
    <div id="progress<%= index %>" style="height: 16px;"></div>
    <script>
        var ctx = "progress<%= index %>"
        var bar = new ProgressBar.Line(document.getElementById(ctx), {
            strokeWidth: 1.2,
            easing: 'easeInOut',
            duration: 1400,
            color: '#A0A0A0',
            trailColor: '#EEEEEE',
            trailWidth: 1,
            svgStyle: {width: '100%', height: '100%'},
            from: {color: '#FF3333'},
            to: {color: '#99FF33'},
            step: (state, bar) => {
                bar.path.setAttribute('stroke', state.color);
                bar.setText(Math.round(bar.value() * 100) + ' %');
            }
        });

        bar.animate(<%= file.line_coverage %>);  // Number from 0.0 to 1.0
    </script>
    <div class="table-responsive">
      <table class="table">
        <thead>
        <tr>
          <th><div class="th-inner sortable both">Function</div></th>
          <th>Covered lines</th>
          <th>Line coverage</th>
          <th>Line number</th>
          <th>Execution count</th>
          <th>Executable lines</th>
<!--          <th colspan="3"></th>-->
        </tr>
        </thead>

        <tbody>
        <% sorted_functions(file.functions).each do |function| %>
          <tr class=<%= row_class(function) %> >
            <td><%= function.name %></td>
            <td><%= function.covered_lines %></td>
            <td><%= number_to_code_coverage_percentage(function.line_coverage) %></td>
            <td><%= function.line_number %></td>
            <td><%= function.execution_count %></td>
            <td><%= function.executable_lines %></td>
<!--            <td><%#= link_to 'Show', function %></td>-->
<!--            <td><%#= link_to 'Edit', edit_function_path(function) %></td>-->
<!--            <td><%#= link_to 'Destroy', function, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  <% end %>
<% end %>

<p>
  <strong>Covered lines:</strong>
  <%= @coverage_report.covered_lines %>
</p>

<p>
  <strong>Line coverage:</strong>
  <%= @coverage_report.line_coverage %>
</p>

<p>
  <strong>Coverage targets:</strong>
  <%= @coverage_report.coverage_targets %>
</p>

<p>
  <strong>Executable lines:</strong>
  <%= @coverage_report.executable_lines %>
</p>

<%= link_to 'Edit', edit_coverage_report_path(@coverage_report) %> |
<%= link_to 'Back', coverage_reports_path %>